import type {Metadata} from "next";
import Navbar from "@/components/navbar";
import {Poppins} from "next/font/google";
import "./globals.css";

//included poppins font as in the ui design
const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
      <header>
        <Navbar />
      </header>
      <main>
        {children}
      </main>
      </body>
    </html>
  );
}
